# Generated by Django 5.2.8 on 2025-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_kp', models.CharField(help_text='Код за класифікатором професій (напр. 2411.2)', max_length=15, verbose_name='Код КП')),
                ('code_zkpptr', models.CharField(blank=True, help_text='Код загальносоюзного класифікатора (якщо є)', max_length=10, null=True, verbose_name='Код ЗКППТР')),
                ('name', models.CharField(max_length=500, verbose_name='Професійна назва роботи')),
            ],
            options={
                'verbose_name': 'Класифікатор посад',
                'verbose_name_plural': 'Класифікатор посад (ДК 003:2010)',
                'ordering': ['code_kp'],
                'indexes': [models.Index(fields=['code_kp'], name='directories_code_kp_78f986_idx'), models.Index(fields=['name'], name='directories_name_9bf5f4_idx')],
            },
        ),
    ]
