# Generated by Django 5.2.8 on 2025-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Рік')),
                ('min_salary', models.DecimalField(decimal_places=2, default=8000.0, max_digits=10, verbose_name='Мінімальна ЗП (місячна), грн')),
                ('pm_for_able_bodied', models.DecimalField(decimal_places=2, default=3028.0, max_digits=10, verbose_name='Прожитковий мінімум для працездатних осіб, грн')),
                ('pdfo_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Ставка ПДФО, %')),
                ('vz_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Ставка Військового збору, %')),
                ('esv_rate', models.DecimalField(decimal_places=2, default=22.0, max_digits=5, verbose_name='Ставка ЄСВ, %')),
            ],
            options={
                'verbose_name': 'Налаштування показників',
                'verbose_name_plural': 'Налаштування показників',
            },
        ),
    ]
