# Generated by Django 6.0 on 2026-01-18 11:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='Оберіть дату, з якої ці показники стають актуальними', unique=True, verbose_name='Діє з (дата)')),
                ('min_salary', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Мінімальна заробітна плата (місячна)')),
                ('pm_able_bodied', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Прожитковий мінімум (працездатні)')),
                ('pdfo_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Ви впевненні, що значення більше 0,00?'), django.core.validators.MaxValueValidator(Decimal('99.99'), message='Ви впевненні, що значення менше 100?')], verbose_name='Ставка ПДФО, %')),
                ('vz_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Військовий збір, %')),
                ('esv_rate', models.DecimalField(decimal_places=2, default=22.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ЄСВ, %')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'social_settings',
                'ordering': ['-effective_from'],
            },
        ),
    ]
