# Generated by Django 5.2.8 on 2025-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Прізвище', models.CharField(max_length=100)),
                ("Ім'я", models.CharField(max_length=100)),
                ('По батькові', models.CharField(max_length=100)),
                ('ПІБ', models.CharField(max_length=100)),
                ('День народження', models.DateField(blank=True)),
                ('Стать', models.CharField(choices=[('male', 'чоловіча'), ('female', 'жіноча')])),
                ('Співробітник', models.BooleanField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('Працює', models.BooleanField(default=False)),
            ],
        ),
    ]
