# Generated by Django 5.2.8 on 2025-12-23 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Номер наказу', models.CharField(max_length=8)),
                ('Короткий зміст', models.TextField(blank=True, max_length=200)),
                ('Дата прийняття', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
